# ============================================
# AI-POWERED INSIGHTS (Minimal - reads from MongoDB)
# ============================================

import streamlit as st
from datetime import datetime

# Note: This module is minimal because insights will be generated
# by your Docker pipeline and stored in MongoDB.
# This function only RETRIEVES and DISPLAYS them.

def render_insights_section(is_premium):
    """Render the insights section (premium only)."""
    if not is_premium:
        return
    
    st.subheader("🧠 Weekly Intelligence Briefing")
    
    # Create two columns for the insights section
    insight_col1, insight_col2 = st.columns([3, 1])
    
    with insight_col1:
        st.markdown("""
        <div style="background-color: #F0F7FF; padding: 15px; border-radius: 10px; border-left: 5px solid #00C2FF;">
            <p style="margin: 0; color: #333;">Generate AI-powered insights from the last 7 days of market signals. Get actionable intelligence for your recruitment strategy.</p>
        </div>
        """, unsafe_allow_html=True)
    
    with insight_col2:
        generate = st.button("🔮 Generate Insights", use_container_width=True)
    
    if generate:
        with st.spinner("Analyzing 7 days of market signals with AI..."):
            # TODO: In production, this will read from MongoDB where your Docker pipeline
            # stores weekly insights. For now, placeholder.
            
            st.success("✅ Insights generated!")
            
            # Placeholder insights - will be replaced with real data from MongoDB
            st.markdown("""
            <div style="background-color: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-top: 15px;">
                <h4 style="color: #0A0F1F; margin-top: 0;">Key Takeaways This Week</h4>
                <ul style="list-style-type: none; padding-left: 0;">
                    <li style="margin-bottom: 10px;">🔹 <strong>Layoffs accelerating:</strong> Meta planning 16,000 cuts, VW restructuring 50,000 by 2030</li>
                    <li style="margin-bottom: 10px;">🔹 <strong>Labor unrest:</strong> Lufthansa pilots strike disrupting hundreds of flights</li>
                    <li style="margin-bottom: 10px;">🔹 <strong>AI transformation:</strong> SAP restructuring around AI, Oracle cuts due to AI pressure</li>
                    <li style="margin-bottom: 10px;">🔹 <strong>Watch next week:</strong> More airline strikes, continued tech sector volatility</li>
                </ul>
                <p style="color: #666; font-size: 0.9rem; margin-bottom: 0;">⚡ Full AI integration coming soon with weekly reports</p>
            </div>
            """, unsafe_allow_html=True)
            
            # Download button for insights
            st.download_button(
                "📥 Download Insights",
                data="Weekly insights will be generated by Docker pipeline",
                file_name=f"career_insights_{datetime.now().strftime('%Y%m%d')}.txt",
                use_container_width=True
            )
    else:
        st.info("👆 Click 'Generate Insights' to get AI-powered analysis of the last 7 days.")